name = "DecisionMakingUtils"
uuid = "e21ee072-cbb1-4ecc-b257-6a793c43976a"
authors = ["Scott Jordan"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"

[compat]
julia = "1.5"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
